/*
 This code belongs to the "Em casa" project, an application to monitoring the symptons 
of covid-19 and help people to take care on theyr quarentine period. Most of the project are simple inserts,
but, if you are reading this code for the first time, you'll find some important coments for some
especific parts of the code.
 */
package visao;




import dao.PacienteDao;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import servicos.PacienteServicos;

/**
 *
 * @author user
 */
public class GUIAdicionarPessoa extends javax.swing.JInternalFrame {
    modelo.Paciente p = new modelo.Paciente();
    
    
    /* This vector runs throught the user class to get the user's identification, 
    the function of this vector is to show to the user the name of the responsables
    and sent the value to the database
    */
    
    Vector<Integer> id_responsavel =  new Vector<Integer>();
    
    
    /*
        This method is responsable to bring the name and code of the responsables to
        take care of the persons on isolation. It starts with the initComponents to bring the
        values it right at the moment that the application is started, letting the user see the list
        at any moment, doesn't requiring any other action.
        */
    
    public void restaurarUsuarioCBX(){
        try{
            PacienteDao paciente = new PacienteDao();
            ResultSet rs = paciente.buscarResponsavel();
            
            while (rs.next()){
                id_responsavel.addElement(rs.getInt(1));
                cbxResponsavel.addItem(rs.getString(2));
            }
            
        }
        catch (SQLException e){
            
        }
    }
    
    
    
    public void adicionar(){
        try{
            /*The -1 at the end of the code is responsabel to don't let the user 
            atribute a null value to the fild, if this simple part of the code be
            removed it can generate an application error pointig a missing foreign key value, so, don't change this.
            */
            int cod_usuario = id_responsavel.get(cbxResponsavel.getSelectedIndex()-1);
            p.setCod_usuario(cod_usuario);
            p.setNome(jtfNome.getText());
            p.setMedicacao(jTextArea1.getText());
            p.setInicioIsolamento(jftfDataInicio.getText());
            if(jcFebre.isSelected()){
               p.setFebre(0);
            }
            else {
                p.setFebre(1);
            }
            
            if(jcTosseSeca.isSelected()){
                p.setTosse(0);
            }
            else{
                p.setTosse(1);
            }
            
            if(jcDorDeCabeça.isSelected()){
                p.setDorDeCabeca(0);
            }
            else{
                 p.setDorDeCabeca(1);
            }
            
            if(jcCansaco.isSelected()){
                p.setCansaco(0);
            }
            else{
                p.setCansaco(1);
            }
            
            if(jcDificuldadeParaRespirar.isSelected()){
                p.setDifRespirar(0);
            }
            else{
                p.setDifRespirar(1);
            }
            
            if(jcSemSintomas.isSelected()){
                p.setSemSintomas(0);
            }
            else{
                p.setSemSintomas(1);
            }
        
        PacienteServicos ps = servicos.ServicosFactory.getPacienteServicos();
        ps.cadastrarPaciente(p);
        
        /* The SQLException here comes from the class PacienteDAO, the getMessage was added to alert if some database error occurs.
           if the application points an error when running go direct to this class, it will probably be a parameter error or even
           a digitation problem at the MySQL request. 
        */
        JOptionPane.showMessageDialog(null, "PACIENTE ADIONADO: ","Cadastro",JOptionPane.WARNING_MESSAGE);
        }catch (Exception e) {
            JOptionPane.showMessageDialog(
            rootPane,
            "Erro! "+e.getMessage(),
            "erro",
            JOptionPane.ERROR_MESSAGE);
        }
        }
    
    public void limparCampos(){
        jtfNome.setText(null);
        jftfDataInicio.setText(null);
        cbxResponsavel.setSelectedIndex(0);
        jcCansaco.setSelected(false);
        jcDificuldadeParaRespirar.setSelected(false);
        jcDorDeCabeça.setSelected(false);
        jcFebre.setSelected(false);
        jcSemSintomas.setSelected(false);
        jcTosseSeca.setSelected(false);
        jTextArea1.setText(null);
        
    }
    /**
     * Creates new form GUIAdicionarPessoa
     */
    public GUIAdicionarPessoa() {
        initComponents();
        
        restaurarUsuarioCBX();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCabecalhoAdicionarPessoa = new javax.swing.JPanel();
        jlCabecalhoAdicionaPessoa = new javax.swing.JLabel();
        jlNomePessoa = new javax.swing.JLabel();
        jlDataInicio = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jlCabecalhoSintomas = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jcFebre = new javax.swing.JCheckBox();
        jcTosseSeca = new javax.swing.JCheckBox();
        jcDorDeCabeça = new javax.swing.JCheckBox();
        jcCansaco = new javax.swing.JCheckBox();
        jcDificuldadeParaRespirar = new javax.swing.JCheckBox();
        jcSemSintomas = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jbSalvarPessoa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbxResponsavel = new javax.swing.JComboBox<>();
        jftfDataInicio = new javax.swing.JFormattedTextField();

        setClosable(true);

        jpCabecalhoAdicionarPessoa.setBackground(new java.awt.Color(51, 204, 255));

        jlCabecalhoAdicionaPessoa.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        jlCabecalhoAdicionaPessoa.setForeground(new java.awt.Color(255, 255, 255));
        jlCabecalhoAdicionaPessoa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCabecalhoAdicionaPessoa.setText("ADICIONAR PESSOA");

        javax.swing.GroupLayout jpCabecalhoAdicionarPessoaLayout = new javax.swing.GroupLayout(jpCabecalhoAdicionarPessoa);
        jpCabecalhoAdicionarPessoa.setLayout(jpCabecalhoAdicionarPessoaLayout);
        jpCabecalhoAdicionarPessoaLayout.setHorizontalGroup(
            jpCabecalhoAdicionarPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCabecalhoAdicionarPessoaLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jlCabecalhoAdicionaPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jpCabecalhoAdicionarPessoaLayout.setVerticalGroup(
            jpCabecalhoAdicionarPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCabecalhoAdicionarPessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlCabecalhoAdicionaPessoa)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jlNomePessoa.setText("Nome:");

        jlDataInicio.setText("Data Início do Isolamento:");

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        jlCabecalhoSintomas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlCabecalhoSintomas.setForeground(new java.awt.Color(255, 255, 255));
        jlCabecalhoSintomas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCabecalhoSintomas.setText("Sintomas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jlCabecalhoSintomas, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlCabecalhoSintomas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jcFebre.setBackground(new java.awt.Color(255, 255, 255));
        jcFebre.setText("Febre");

        jcTosseSeca.setBackground(new java.awt.Color(255, 255, 255));
        jcTosseSeca.setText("Tosse Seca");

        jcDorDeCabeça.setBackground(new java.awt.Color(255, 255, 255));
        jcDorDeCabeça.setText("Dor de Cabeça");

        jcCansaco.setBackground(new java.awt.Color(255, 255, 255));
        jcCansaco.setText("Cansaço");

        jcDificuldadeParaRespirar.setBackground(new java.awt.Color(255, 255, 255));
        jcDificuldadeParaRespirar.setText("Dificuldade para respirar");

        jcSemSintomas.setBackground(new java.awt.Color(255, 255, 255));
        jcSemSintomas.setText("Sem Sintomas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcDorDeCabeça)
                    .addComponent(jcTosseSeca)
                    .addComponent(jcFebre))
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jcDificuldadeParaRespirar)
                        .addGap(53, 53, 53))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcCansaco)
                            .addComponent(jcSemSintomas))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jcCansaco)
                        .addGap(18, 18, 18)
                        .addComponent(jcDificuldadeParaRespirar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jcSemSintomas))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(15, Short.MAX_VALUE)
                        .addComponent(jcFebre)
                        .addGap(18, 18, 18)
                        .addComponent(jcTosseSeca)
                        .addGap(18, 18, 18)
                        .addComponent(jcDorDeCabeça)))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 204));

        jLabel1.setBackground(new java.awt.Color(0, 102, 204));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Medicação");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jbSalvarPessoa.setBackground(new java.awt.Color(51, 204, 255));
        jbSalvarPessoa.setText("Salvar");
        jbSalvarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarPessoaActionPerformed(evt);
            }
        });

        jLabel2.setText("Responsável:");

        cbxResponsavel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        cbxResponsavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxResponsavelActionPerformed(evt);
            }
        });

        try {
            jftfDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCabecalhoAdicionarPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jbSalvarPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jlDataInicio)
                    .addComponent(jlNomePessoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jftfDataInicio)
                    .addComponent(jtfNome, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(cbxResponsavel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpCabecalhoAdicionarPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNomePessoa)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDataInicio)
                    .addComponent(jftfDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbSalvarPessoa)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalvarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarPessoaActionPerformed
        adicionar();
        limparCampos();
    }//GEN-LAST:event_jbSalvarPessoaActionPerformed

    private void cbxResponsavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxResponsavelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxResponsavelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxResponsavel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbSalvarPessoa;
    private javax.swing.JCheckBox jcCansaco;
    private javax.swing.JCheckBox jcDificuldadeParaRespirar;
    private javax.swing.JCheckBox jcDorDeCabeça;
    private javax.swing.JCheckBox jcFebre;
    private javax.swing.JCheckBox jcSemSintomas;
    private javax.swing.JCheckBox jcTosseSeca;
    private javax.swing.JFormattedTextField jftfDataInicio;
    private javax.swing.JLabel jlCabecalhoAdicionaPessoa;
    private javax.swing.JLabel jlCabecalhoSintomas;
    private javax.swing.JLabel jlDataInicio;
    private javax.swing.JLabel jlNomePessoa;
    private javax.swing.JPanel jpCabecalhoAdicionarPessoa;
    private javax.swing.JTextField jtfNome;
    // End of variables declaration//GEN-END:variables

    
    }

