/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author user
 */
public class GUITelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public GUITelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jbEmergencia = new javax.swing.JButton();
        jbCuidadosCasa = new javax.swing.JButton();
        jbCuidadosPessoais = new javax.swing.JButton();
        jbMonitorar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmUsuario = new javax.swing.JMenu();
        jmiCadastrar = new javax.swing.JMenuItem();
        jmiExcluir = new javax.swing.JMenuItem();
        jmiSobre = new javax.swing.JMenuItem();
        jmPessoa = new javax.swing.JMenu();
        jmiAdicionar = new javax.swing.JMenuItem();
        jmiMonitorar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(755, 670));

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(755, 700));

        jbEmergencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/emergencia.png"))); // NOI18N
        jbEmergencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEmergenciaActionPerformed(evt);
            }
        });

        jbCuidadosCasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/casa.png"))); // NOI18N
        jbCuidadosCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCuidadosCasaActionPerformed(evt);
            }
        });

        jbCuidadosPessoais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/higiene.png"))); // NOI18N
        jbCuidadosPessoais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCuidadosPessoaisActionPerformed(evt);
            }
        });

        jbMonitorar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/olho.png"))); // NOI18N
        jbMonitorar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbMonitorarMousePressed(evt);
            }
        });
        jbMonitorar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMonitorarActionPerformed(evt);
            }
        });

        jLabel1.setText("CUIDADOS EM CASA");

        jLabel2.setText("MONITORAR");

        jLabel3.setText("CUIDADOS PESSOAIS");

        jLabel4.setText("LIGAÇÃO DE EMERGÊNCIA");

        jDesktopPane1.setLayer(jbEmergencia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jbCuidadosCasa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jbCuidadosPessoais, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jbMonitorar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbMonitorar)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2))
                    .addComponent(jLabel3)
                    .addComponent(jbCuidadosPessoais))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jbCuidadosCasa)
                            .addComponent(jbEmergencia))
                        .addGap(152, 152, 152))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(141, 141, 141))))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbCuidadosCasa)
                    .addComponent(jbMonitorar))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(65, 65, 65)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbEmergencia)
                    .addComponent(jbCuidadosPessoais))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(80, 80, 80))
        );

        jmUsuario.setText("Usuário");

        jmiCadastrar.setText("Cadastrar");
        jmiCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastrarActionPerformed(evt);
            }
        });
        jmUsuario.add(jmiCadastrar);

        jmiExcluir.setText("Excluir");
        jmiExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiExcluirActionPerformed(evt);
            }
        });
        jmUsuario.add(jmiExcluir);

        jmiSobre.setText("Sobre");
        jmiSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSobreActionPerformed(evt);
            }
        });
        jmUsuario.add(jmiSobre);

        jMenuBar1.add(jmUsuario);

        jmPessoa.setText("Pessoa");

        jmiAdicionar.setText("Adicionar Pessoa");
        jmiAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAdicionarActionPerformed(evt);
            }
        });
        jmPessoa.add(jmiAdicionar);

        jmiMonitorar.setText("Monitorar Pessoas");
        jmiMonitorar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMonitorarActionPerformed(evt);
            }
        });
        jmPessoa.add(jmiMonitorar);

        jMenuBar1.add(jmPessoa);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSobreActionPerformed
        GUISobreUsuario su = new GUISobreUsuario();
        jDesktopPane1.add(su);
        su.setVisible(true);
        
    }//GEN-LAST:event_jmiSobreActionPerformed

    private void jmiExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiExcluirActionPerformed
        GUIExcluirUsuario eu = new GUIExcluirUsuario();
        jDesktopPane1.add(eu);
        eu.setVisible(true);
    }//GEN-LAST:event_jmiExcluirActionPerformed

    private void jmiCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastrarActionPerformed
         GUICadastroUsuario cu = new GUICadastroUsuario();
        jDesktopPane1.add(cu);
        cu.setVisible(true);
    }//GEN-LAST:event_jmiCadastrarActionPerformed

    private void jmiMonitorarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMonitorarActionPerformed
        GUIMonitorarPessoa mp = new GUIMonitorarPessoa();
        jDesktopPane1.add(mp);
        mp.setVisible(true);
    }//GEN-LAST:event_jmiMonitorarActionPerformed

    private void jmiAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAdicionarActionPerformed
        GUIAdicionarPessoa ap = new GUIAdicionarPessoa();
        jDesktopPane1.add(ap);
        ap.setVisible(true);
    }//GEN-LAST:event_jmiAdicionarActionPerformed

    private void jbEmergenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEmergenciaActionPerformed
        GUIEmergencia mp = new GUIEmergencia();
        jDesktopPane1.add(mp);
        mp.setVisible(true);
    }//GEN-LAST:event_jbEmergenciaActionPerformed

    private void jbMonitorarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMonitorarActionPerformed
        GUIMonitorar mp = new GUIMonitorar();
        jDesktopPane1.add(mp);
        mp.setVisible(true);
    }//GEN-LAST:event_jbMonitorarActionPerformed

    private void jbMonitorarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbMonitorarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbMonitorarMousePressed

    private void jbCuidadosCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCuidadosCasaActionPerformed
        GUICuidadosCasa mp = new GUICuidadosCasa();
        jDesktopPane1.add(mp);
        mp.setVisible(true);
    }//GEN-LAST:event_jbCuidadosCasaActionPerformed

    private void jbCuidadosPessoaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCuidadosPessoaisActionPerformed
        GUICuidadosPessoais mp = new GUICuidadosPessoais();
        jDesktopPane1.add(mp);
        mp.setVisible(true);
    }//GEN-LAST:event_jbCuidadosPessoaisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUITelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUITelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUITelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUITelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUITelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton jbCuidadosCasa;
    private javax.swing.JButton jbCuidadosPessoais;
    private javax.swing.JButton jbEmergencia;
    private javax.swing.JButton jbMonitorar;
    private javax.swing.JMenu jmPessoa;
    private javax.swing.JMenu jmUsuario;
    private javax.swing.JMenuItem jmiAdicionar;
    private javax.swing.JMenuItem jmiCadastrar;
    private javax.swing.JMenuItem jmiExcluir;
    private javax.swing.JMenuItem jmiMonitorar;
    private javax.swing.JMenuItem jmiSobre;
    // End of variables declaration//GEN-END:variables
}
